---
S1:
   hostname: 192.168.122.11
   platform: 'ios'
   username: 'admin'
   password: 'admin'
   groups:
        - sw       
s2:
   hostname: 192.168.122.22
   platform: 'ios'
   username: 'admin'
   password: 'admin'
   groups:
        - sw
s3:
   hostname: 192.168.122.133
   platform: 'ios'
   username: 'admin'
   password: 'admin'
   groups:
        - sw
s4:
   hostname: 192.168.122.144
   platform: 'ios'
   username: 'admin'
   password: 'admin'
   groups:
        - sw
s5:
   hostname: 192.168.122.155
   platform: 'ios'
   username: 'admin'
   password: 'admin'
   groups:
        - sw
